# Generated by Django 4.0.5 on 2022-06-25 00:33

import autofillout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saved_boo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('content', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='saved_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('content', autofillout.models.ListField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='saved_str',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=25)),
            ],
        ),
    ]
