# Generated by Django 4.0.5 on 2022-06-29 12:57

import autofillout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autofillout', '0003_alter_saved_boo_content_alter_saved_str_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='do_not_delete',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=25, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='saved_list',
            name='content',
            field=autofillout.models.ListField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name='saved_str',
            name='content',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
