# Generated by Django 4.0.5 on 2022-07-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autofillout', '0004_do_not_delete_alter_saved_list_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='do_not_delete',
        ),
    ]
